In [2]:
max_gen_len = 500
span_len = 3
mask_p = 0.5
import torch

num_spans = max_gen_len // span_len
num_masked_spans = round(mask_p * num_spans)
possible_span_starts: torch.Tensor = (torch.arange(0, num_spans) * 3).long()
selected_span_starts_to_mask = possible_span_starts[torch.randperm(possible_span_starts.shape[0])[:num_masked_spans]]


In [3]:
selected_span_starts_to_mask

tensor([282, 165,  39,  63, 423, 435, 444, 108,  69, 120, 477, 327, 132, 306,
        303, 234, 201, 468, 483, 159, 210, 372,  54, 330, 426,  48, 228, 471,
        258, 369, 339, 138, 144, 357, 195, 450, 162, 114, 441,  18, 153, 459,
        237,  60, 318, 360, 267, 240, 294, 465, 390,  57, 249, 192, 123, 405,
        174, 207, 279, 147,   0, 222, 429, 408,   3, 189, 255, 447, 150, 246,
        141, 432, 345, 348, 396, 105,  87, 285, 177, 399, 411,  45, 414])

In [10]:
#mask = self._construct_spans_mask(span_starts = selected_span_starts_to_mask, T=gen_codes.shape[2], device=device)
mask = torch.full((num_spans*3+2,), False)
mask[selected_span_starts_to_mask] = True
mask

tensor([ True, False, False,  True, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False,  True, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False,  True, False, False,  True, False,
        False, False, False, False,  True, False, False,  True, False, False,
         True, False, False,  True, False, False, False, False, False,  True,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True, False, False,  True, False,
        False, False, False, False,  True, False, False, False, False, False,
         True, False, False,  True, False, False, False, False, 

In [11]:
gen_codes = torch.stack([torch.arange(max_gen_len), torch.arange(max_gen_len), torch.arange(max_gen_len), torch.arange(max_gen_len)]).unsqueeze(0)
stage = 1
mask_id = -1
gen_codes[:, [stage], :] = torch.where(mask, mask_id, gen_codes[:, stage])


In [14]:
mask, gen_codes, gen_codes[:, [1], :6]

(tensor([ True, False, False,  True, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False,  True, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,  True,
         False, False, False, False, False,  True, False, False,  True, False,
         False, False, False, False,  True, False, False,  True, False, False,
          True, False, False,  True, False, False, False, False, False,  True,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False,  True, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False,  True, False, False,  True, False,
         False, False, False, False,  True, False, False, False, False, False,
          True, False, False,  True, False, False, F